### 
//Create a New Comment
POST http://localhost:3004/comments
Content-Type: application/json

{
    "postId": "677c098ac99318873df51df0",
    "text": "This is a comment2.",
    "sender": "User123"
}

### 
//Get All Comments
GET http://localhost:3004/comments

### Get
//Comments by Post ID
GET http://localhost:3004/comments/post/677c098ac99318873df51df0

### 
//Update a Comment
PUT http://localhost:3004/comments/677c0a15c99318873df51df7
Content-Type: application/json

{
    "text": "This is an updated comment.",
    "sender": "User123"
}

### 
//Delete a Comment
DELETE http://localhost:3004/comments/677a5a2a73adf8e549624ae8
