###
//Get all posts
GET http://localhost:3004/post

###
// Get Posts by Sender
GET http://localhost:3004/post/by-sender?sender=User1

###
//Get post by ID
GET http://localhost:3004/post/677c098ac99318873df51df0

###
//Create new post
POST http://localhost:3004/post
Content-Type: application/json

{
    "title": "My First Post",
    "content": "This is my Second post!",
    "sender": "User1"
}

### 
//Update a Post
PUT http://localhost:3004/post/677c098ac99318873df51df0
Content-Type: application/json

{
    "title": "Updated Title",
    "content": "Updated content!",
    "sender": "User123"
}

### 
//Delete a Post
DELETE http://localhost:3004/post/677a524057db0c76a81b25af