### 
//Create a New Comment
POST http://localhost:3004/comments
Content-Type: application/json

{
    "postId": "677c0d8a0be6c5b6ee276e4d",
    "text": "This is a comment2.",
    "sender": "User123"
}

### 
//Get All Comments
GET http://localhost:3004/comments

### Get
//Comments by Post ID
GET http://localhost:3004/comments/post/677c0d8a0be6c5b6ee276e4d

### 
//Update a Comment
PUT http://localhost:3004/comments/677c0de20be6c5b6ee276e58
Content-Type: application/json

{
    "text": "This is an updated comment.",
    "sender": "User123"
}

### 
//Delete a Comment
DELETE http://localhost:3004/comments/677a5a2a73adf8e549624ae8
